// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD993H1J0moDW7OsgSRNGk7mRydI8cockw',
    appId: '1:829657639759:web:71b068dd29e8c80da6b33a',
    messagingSenderId: '829657639759',
    projectId: 'riytouappproject',
    authDomain: 'riytouappproject.firebaseapp.com',
    storageBucket: 'riytouappproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaiZ67NDQumMrQ1oCgvfJM_I_B4RjB4No',
    appId: '1:829657639759:android:355a431e78830084a6b33a',
    messagingSenderId: '829657639759',
    projectId: 'riytouappproject',
    storageBucket: 'riytouappproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw851NTwhXzHpbvlXizYx9sQR_6uRV-yY',
    appId: '1:829657639759:ios:69e0d59ccb7254afa6b33a',
    messagingSenderId: '829657639759',
    projectId: 'riytouappproject',
    storageBucket: 'riytouappproject.appspot.com',
    iosBundleId: 'com.example.testapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw851NTwhXzHpbvlXizYx9sQR_6uRV-yY',
    appId: '1:829657639759:ios:36a88f584541a15ba6b33a',
    messagingSenderId: '829657639759',
    projectId: 'riytouappproject',
    storageBucket: 'riytouappproject.appspot.com',
    iosBundleId: 'com.example.testapp1.RunnerTests',
  );
}
